<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\LabTestMaster;

class LabTestMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $labTests = [
            // Blood Tests
            [
                'test_name' => 'Complete Blood Count (CBC)',
                'test_category' => 'Blood Test',
                'test_code' => 'CBC001',
                'test_description' => 'A complete blood count test measures various components of blood including red blood cells, white blood cells, hemoglobin, hematocrit, and platelets.',
                'test_price' => 500.00,
                'test_discount' => 10.00,
                'test_image' => 'lab-tests/blood-test-cbc.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Blood Glucose (Fasting)',
                'test_category' => 'Blood Test',
                'test_code' => 'BGL001',
                'test_description' => 'Fasting blood glucose test measures the amount of glucose in your blood after fasting for at least 8 hours.',
                'test_price' => 200.00,
                'test_discount' => 5.00,
                'test_image' => 'lab-tests/blood-glucose.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Lipid Profile',
                'test_category' => 'Blood Test',
                'test_code' => 'LIP001',
                'test_description' => 'Lipid profile test measures cholesterol levels including total cholesterol, HDL, LDL, and triglycerides.',
                'test_price' => 600.00,
                'test_discount' => 15.00,
                'test_image' => 'lab-tests/lipid-profile.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Liver Function Test (LFT)',
                'test_category' => 'Blood Test',
                'test_code' => 'LFT001',
                'test_description' => 'Liver function tests measure various enzymes and proteins to assess liver health and function.',
                'test_price' => 800.00,
                'test_discount' => 12.00,
                'test_image' => 'lab-tests/liver-function.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Kidney Function Test (KFT)',
                'test_category' => 'Blood Test',
                'test_code' => 'KFT001',
                'test_description' => 'Kidney function tests measure creatinine, urea, and other markers to assess kidney health.',
                'test_price' => 700.00,
                'test_discount' => 10.00,
                'test_image' => 'lab-tests/kidney-function.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Thyroid Function Test (TFT)',
                'test_category' => 'Blood Test',
                'test_code' => 'TFT001',
                'test_description' => 'Thyroid function tests measure TSH, T3, and T4 levels to evaluate thyroid gland function.',
                'test_price' => 900.00,
                'test_discount' => 15.00,
                'test_image' => 'lab-tests/thyroid-function.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Hemoglobin (Hb)',
                'test_category' => 'Blood Test',
                'test_code' => 'HB001',
                'test_description' => 'Hemoglobin test measures the amount of hemoglobin in red blood cells to check for anemia.',
                'test_price' => 150.00,
                'test_discount' => 0.00,
                'test_image' => 'lab-tests/hemoglobin.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Vitamin D (25-OH)',
                'test_category' => 'Blood Test',
                'test_code' => 'VD001',
                'test_description' => 'Vitamin D test measures the level of 25-hydroxyvitamin D in the blood to assess vitamin D status.',
                'test_price' => 1200.00,
                'test_discount' => 20.00,
                'test_image' => 'lab-tests/vitamin-d.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Vitamin B12',
                'test_category' => 'Blood Test',
                'test_code' => 'VB12001',
                'test_description' => 'Vitamin B12 test measures the level of vitamin B12 in the blood to detect deficiency.',
                'test_price' => 1000.00,
                'test_discount' => 15.00,
                'test_image' => 'lab-tests/vitamin-b12.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'HbA1c (Glycated Hemoglobin)',
                'test_category' => 'Blood Test',
                'test_code' => 'HBA1C001',
                'test_description' => 'HbA1c test measures average blood sugar levels over the past 2-3 months.',
                'test_price' => 600.00,
                'test_discount' => 10.00,
                'test_image' => 'lab-tests/hba1c.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Iron Studies',
                'test_category' => 'Blood Test',
                'test_code' => 'IRN001',
                'test_description' => 'Iron studies measure iron levels, ferritin, and transferrin to assess iron deficiency or overload.',
                'test_price' => 750.00,
                'test_discount' => 12.00,
                'test_image' => 'lab-tests/iron-studies.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'ESR (Erythrocyte Sedimentation Rate)',
                'test_category' => 'Blood Test',
                'test_code' => 'ESR001',
                'test_description' => 'ESR test measures how quickly red blood cells settle at the bottom of a test tube, indicating inflammation.',
                'test_price' => 180.00,
                'test_discount' => 5.00,
                'test_image' => 'lab-tests/esr.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'CRP (C-Reactive Protein)',
                'test_category' => 'Blood Test',
                'test_code' => 'CRP001',
                'test_description' => 'CRP test measures the level of C-reactive protein in blood, indicating inflammation or infection.',
                'test_price' => 400.00,
                'test_discount' => 8.00,
                'test_image' => 'lab-tests/crp.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Blood Group & Rh Factor',
                'test_category' => 'Blood Test',
                'test_code' => 'BGR001',
                'test_description' => 'Blood group test determines your ABO blood type and Rh factor (positive or negative).',
                'test_price' => 200.00,
                'test_discount' => 0.00,
                'test_image' => 'lab-tests/blood-group.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'RBC Count',
                'test_category' => 'Blood Test',
                'test_code' => 'RBC001',
                'test_description' => 'Red blood cell count measures the number of red blood cells in a blood sample.',
                'test_price' => 250.00,
                'test_discount' => 5.00,
                'test_image' => 'lab-tests/rbc-count.jpg',
                'test_status' => 'active',
            ],

            // Urine Tests
            [
                'test_name' => 'Complete Urine Analysis',
                'test_category' => 'Urine Test',
                'test_code' => 'CUA001',
                'test_description' => 'Complete urine analysis examines the physical, chemical, and microscopic properties of urine.',
                'test_price' => 250.00,
                'test_discount' => 5.00,
                'test_image' => 'lab-tests/urine-analysis.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Urine Culture & Sensitivity',
                'test_category' => 'Urine Test',
                'test_code' => 'UCS001',
                'test_description' => 'Urine culture test identifies bacteria in urine and determines antibiotic sensitivity.',
                'test_price' => 800.00,
                'test_discount' => 12.00,
                'test_image' => 'lab-tests/urine-culture.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => '24-Hour Urine Protein',
                'test_category' => 'Urine Test',
                'test_code' => 'UPR001',
                'test_description' => '24-hour urine protein test measures the amount of protein excreted in urine over 24 hours.',
                'test_price' => 600.00,
                'test_discount' => 10.00,
                'test_image' => 'lab-tests/urine-protein.jpg',
                'test_status' => 'active',
            ],

            // Imaging Tests
            [
                'test_name' => 'Chest X-Ray',
                'test_category' => 'Imaging Test',
                'test_code' => 'CXR001',
                'test_description' => 'Chest X-ray examines the lungs, heart, and chest cavity for abnormalities.',
                'test_price' => 500.00,
                'test_discount' => 10.00,
                'test_image' => 'lab-tests/chest-xray.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Ultrasound Abdomen',
                'test_category' => 'Imaging Test',
                'test_code' => 'USAB001',
                'test_description' => 'Abdominal ultrasound uses sound waves to examine organs in the abdomen.',
                'test_price' => 1000.00,
                'test_discount' => 15.00,
                'test_image' => 'lab-tests/ultrasound-abdomen.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'CT Scan Head',
                'test_category' => 'Imaging Test',
                'test_code' => 'CTH001',
                'test_description' => 'CT scan of the head provides detailed images of the brain and skull.',
                'test_price' => 3500.00,
                'test_discount' => 20.00,
                'test_image' => 'lab-tests/ct-scan-head.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'MRI Brain',
                'test_category' => 'Imaging Test',
                'test_code' => 'MRB001',
                'test_description' => 'MRI of the brain uses magnetic fields to produce detailed images of brain structures.',
                'test_price' => 6000.00,
                'test_discount' => 25.00,
                'test_image' => 'lab-tests/mri-brain.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'ECG (Electrocardiogram)',
                'test_category' => 'Imaging Test',
                'test_code' => 'ECG001',
                'test_description' => 'ECG records the electrical activity of the heart to detect heart problems.',
                'test_price' => 400.00,
                'test_discount' => 8.00,
                'test_image' => 'lab-tests/ecg.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Ultrasound Pelvis',
                'test_category' => 'Imaging Test',
                'test_code' => 'USPL001',
                'test_description' => 'Pelvic ultrasound examines the reproductive organs and pelvic structures.',
                'test_price' => 1200.00,
                'test_discount' => 15.00,
                'test_image' => 'lab-tests/ultrasound-pelvis.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'X-Ray Spine',
                'test_category' => 'Imaging Test',
                'test_code' => 'XRS001',
                'test_description' => 'Spine X-ray examines the bones and alignment of the spinal column.',
                'test_price' => 600.00,
                'test_discount' => 10.00,
                'test_image' => 'lab-tests/xray-spine.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'CT Scan Chest',
                'test_category' => 'Imaging Test',
                'test_code' => 'CTC001',
                'test_description' => 'CT scan of the chest provides detailed images of the lungs, heart, and chest structures.',
                'test_price' => 4000.00,
                'test_discount' => 20.00,
                'test_image' => 'lab-tests/ct-scan-chest.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'MRI Spine',
                'test_category' => 'Imaging Test',
                'test_code' => 'MRS001',
                'test_description' => 'MRI of the spine provides detailed images of the spinal cord and vertebrae.',
                'test_price' => 7000.00,
                'test_discount' => 25.00,
                'test_image' => 'lab-tests/mri-spine.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Echocardiogram',
                'test_category' => 'Imaging Test',
                'test_code' => 'ECHO001',
                'test_description' => 'Echocardiogram uses ultrasound to create images of the heart and assess its function.',
                'test_price' => 2500.00,
                'test_discount' => 18.00,
                'test_image' => 'lab-tests/echocardiogram.jpg',
                'test_status' => 'active',
            ],

            // Pathology Tests
            [
                'test_name' => 'Pap Smear',
                'test_category' => 'Pathology Test',
                'test_code' => 'PS001',
                'test_description' => 'Pap smear test screens for cervical cancer by examining cervical cells.',
                'test_price' => 800.00,
                'test_discount' => 10.00,
                'test_image' => 'lab-tests/pap-smear.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Biopsy',
                'test_category' => 'Pathology Test',
                'test_code' => 'BIO001',
                'test_description' => 'Biopsy involves removing a small tissue sample for microscopic examination.',
                'test_price' => 2000.00,
                'test_discount' => 15.00,
                'test_image' => 'lab-tests/biopsy.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Fine Needle Aspiration (FNA)',
                'test_category' => 'Pathology Test',
                'test_code' => 'FNA001',
                'test_description' => 'FNA uses a thin needle to extract cells from lumps or masses for examination.',
                'test_price' => 1500.00,
                'test_discount' => 12.00,
                'test_image' => 'lab-tests/fna.jpg',
                'test_status' => 'active',
            ],

            // Serology Tests
            [
                'test_name' => 'HIV Test',
                'test_category' => 'Serology Test',
                'test_code' => 'HIV001',
                'test_description' => 'HIV test detects antibodies or antigens to the Human Immunodeficiency Virus.',
                'test_price' => 500.00,
                'test_discount' => 0.00,
                'test_image' => 'lab-tests/hiv-test.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Hepatitis B Surface Antigen',
                'test_category' => 'Serology Test',
                'test_code' => 'HBS001',
                'test_description' => 'Hepatitis B test detects the presence of Hepatitis B surface antigen in blood.',
                'test_price' => 600.00,
                'test_discount' => 10.00,
                'test_image' => 'lab-tests/hepatitis-b.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Hepatitis C Antibody',
                'test_category' => 'Serology Test',
                'test_code' => 'HVC001',
                'test_description' => 'Hepatitis C test detects antibodies to the Hepatitis C virus.',
                'test_price' => 700.00,
                'test_discount' => 10.00,
                'test_image' => 'lab-tests/hepatitis-c.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'COVID-19 RT-PCR',
                'test_category' => 'Serology Test',
                'test_code' => 'COV001',
                'test_description' => 'COVID-19 RT-PCR test detects the presence of SARS-CoV-2 virus.',
                'test_price' => 800.00,
                'test_discount' => 0.00,
                'test_image' => 'lab-tests/covid-pcr.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Dengue NS1 Antigen',
                'test_category' => 'Serology Test',
                'test_code' => 'DEN001',
                'test_description' => 'Dengue NS1 antigen test detects the dengue virus in early stages of infection.',
                'test_price' => 900.00,
                'test_discount' => 12.00,
                'test_image' => 'lab-tests/dengue-test.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Malaria Parasite Test',
                'test_category' => 'Serology Test',
                'test_code' => 'MAL001',
                'test_description' => 'Malaria parasite test detects the presence of malaria parasites in blood.',
                'test_price' => 300.00,
                'test_discount' => 5.00,
                'test_image' => 'lab-tests/malaria-test.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Typhoid Test (Widal)',
                'test_category' => 'Serology Test',
                'test_code' => 'TYF001',
                'test_description' => 'Widal test detects antibodies against Salmonella typhi, the bacteria causing typhoid.',
                'test_price' => 400.00,
                'test_discount' => 8.00,
                'test_image' => 'lab-tests/typhoid-test.jpg',
                'test_status' => 'active',
            ],

            // Hormone Tests
            [
                'test_name' => 'Progesterone',
                'test_category' => 'Hormone Test',
                'test_code' => 'PROG001',
                'test_description' => 'Progesterone test measures the level of progesterone hormone in blood.',
                'test_price' => 800.00,
                'test_discount' => 12.00,
                'test_image' => 'lab-tests/progesterone.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Testosterone',
                'test_category' => 'Hormone Test',
                'test_code' => 'TES001',
                'test_description' => 'Testosterone test measures the level of testosterone hormone in blood.',
                'test_price' => 900.00,
                'test_discount' => 15.00,
                'test_image' => 'lab-tests/testosterone.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Estrogen',
                'test_category' => 'Hormone Test',
                'test_code' => 'EST001',
                'test_description' => 'Estrogen test measures the level of estrogen hormone in blood.',
                'test_price' => 1000.00,
                'test_discount' => 15.00,
                'test_image' => 'lab-tests/estrogen.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'FSH (Follicle Stimulating Hormone)',
                'test_category' => 'Hormone Test',
                'test_code' => 'FSH001',
                'test_description' => 'FSH test measures the level of follicle-stimulating hormone, important for reproductive health.',
                'test_price' => 750.00,
                'test_discount' => 12.00,
                'test_image' => 'lab-tests/fsh.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'LH (Luteinizing Hormone)',
                'test_category' => 'Hormone Test',
                'test_code' => 'LH001',
                'test_description' => 'LH test measures the level of luteinizing hormone, crucial for ovulation and testosterone production.',
                'test_price' => 750.00,
                'test_discount' => 12.00,
                'test_image' => 'lab-tests/lh.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Prolactin',
                'test_category' => 'Hormone Test',
                'test_code' => 'PRL001',
                'test_description' => 'Prolactin test measures the level of prolactin hormone, which stimulates milk production.',
                'test_price' => 850.00,
                'test_discount' => 13.00,
                'test_image' => 'lab-tests/prolactin.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Cortisol',
                'test_category' => 'Hormone Test',
                'test_code' => 'COR001',
                'test_description' => 'Cortisol test measures the level of cortisol hormone, which helps manage stress and metabolism.',
                'test_price' => 950.00,
                'test_discount' => 14.00,
                'test_image' => 'lab-tests/cortisol.jpg',
                'test_status' => 'active',
            ],

            // Other Tests
            [
                'test_name' => 'Stool Routine & Microscopy',
                'test_category' => 'Stool Test',
                'test_code' => 'STL001',
                'test_description' => 'Stool routine test examines stool sample for parasites, bacteria, and other abnormalities.',
                'test_price' => 300.00,
                'test_discount' => 5.00,
                'test_image' => 'lab-tests/stool-test.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Sputum Culture',
                'test_category' => 'Microbiology Test',
                'test_code' => 'SPT001',
                'test_description' => 'Sputum culture test identifies bacteria or fungi in sputum to diagnose respiratory infections.',
                'test_price' => 900.00,
                'test_discount' => 12.00,
                'test_image' => 'lab-tests/sputum-culture.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Bone Density Scan (DEXA)',
                'test_category' => 'Imaging Test',
                'test_code' => 'DEXA001',
                'test_description' => 'DEXA scan measures bone mineral density to assess osteoporosis risk.',
                'test_price' => 2000.00,
                'test_discount' => 18.00,
                'test_image' => 'lab-tests/dexa-scan.jpg',
                'test_status' => 'active',
            ],
            [
                'test_name' => 'Mammography',
                'test_category' => 'Imaging Test',
                'test_code' => 'MAM001',
                'test_description' => 'Mammography uses X-rays to screen for breast cancer and other breast abnormalities.',
                'test_price' => 1500.00,
                'test_discount' => 15.00,
                'test_image' => 'lab-tests/mammography.jpg',
                'test_status' => 'active',
            ],
        ];

        foreach ($labTests as $labTest) {
            LabTestMaster::updateOrCreate(
                ['test_code' => $labTest['test_code']],
                $labTest
            );
        }

        $this->command->info('Lab Test Masters seeded successfully!');
    }
}
